# Generated by Django 3.2 on 2021-04-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empName', models.CharField(max_length=20)),
                ('empID', models.IntegerField()),
                ('empDept', models.CharField(max_length=10)),
                ('empDOB', models.DateField()),
            ],
        ),
    ]
